name: Build binary

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-ubuntu:
    name: build - ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cmake .

      - run: make bf bfdbg

      - run: ls -lh bin/

      - uses: actions/upload-artifact@v4
        with:
          name: bf-ubuntu
          path: bin/

  build-windows:
    name: build - windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: cmake .

      - run: cmake --build . -t bf -t bfdbg -- /p:Configuration=Release

      - run: dir bin/

      - uses: actions/upload-artifact@v4
        with:
          name: bf-windows
          path: bin/Release/

  build-pylib:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
        python:
          # - "3.10"
          # - "3.11"
          - "3.12"

    name: build pylib - ${{ matrix.os }}-cp${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install -U setuptools

      - run: python setup.py

      - run: |
          mkdir temp
          mv brainfuck.* temp/

      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} temp/

      - uses: actions/upload-artifact@v4
        with:
          name: pylib-${{ matrix.os }}-cp${{ matrix.python }}
          path: temp/
