name: Build binary

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-binary:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
    
    name: build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - run: cmake .

      - run: make bf

      - run: make bfdbg

      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} bin/

      - uses: actions/upload-artifact@v4
        with:
          name: bf-${{ matrix.os }}
          path: bin/

  build-pylib:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
        python:
          # - "3.10"
          # - "3.11"
          - "3.12"

    name: build pylib - ${{ matrix.os }}-cp${{ matrix.python }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install -U setuptools

      - run: python setup.py

      - run: |
          mkdir temp
          mv brainfuck.* temp/
      
      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} temp/

      - uses: actions/upload-artifact@v4
        with:
          name: pylib-${{ matrix.os }}-cp${{ matrix.python }}
          path: temp/
