name: Build binary

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make binary directory
        run: mkdir bin
      - name: Build binary
        run: g++ ./src/*.cpp -O3 -o bin/bf
      - name: Build debug binary
        run: g++ ./src/*.cpp -O3 -o bin/bfdbg -DBF_DEBUG
      - uses: actions/upload-artifact@v4
        with:
          name: bf-ubuntu
          path: bin/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make binary directory
        run: mkdir bin
      - name: Build binary
        run: g++.exe ./src/*.cpp -O3 -o bin/bf.exe
      - name: Build debug binary
        run: g++.exe ./src/*.cpp -O3 -o bin/bfdbg.exe -DBF_DEBUG
      - uses: actions/upload-artifact@v4
        with:
          name: bf-windows
          path: bin/
